MITLibraries/alma-scripts

- cron.d/README
This folder and file are necessary for the logic of the deployment of the Ec2 instance to finish successfully.
> Add cron folder and readme about its use

- README.md
- cron.d/alma-exports
- scripts/Full-Export.sh
- scripts/Update-Export.sh
Summary -
These changes make the scripts "live" on alma-sftp-ec2-prod by removing the comments on the cron jobs.  We also archive the files when we're done with them by moving them to an archive folder.
These changes have been tested in prod and stage, but are not easily testable by the reviewer.
https://mitlibraries.atlassian.net/browse/IMP-2129
> Go live changes

- .github/workflows/tests.yml
- Makefile
- Pipfile
- Pipfile.lock
- cron.d/alma-exports
- cron.d/timdex-exports
- llama/cli.py
- llama/s3.py
- tests/conftest.py
- tests/test_cli.py
- tests/test_s3.py
- Refactors the llama `cli.py` and `s3.py` modules to streamline existing code and make it more reusable
- Adds more robust testing for all known error states
- Updates the cron jobs for daily and monthly export concatenation to use the new llama cli
- Sends the cron-initiated TIMDEX export concat output to a log file for review
Run the command `pipenv run llama concat-timdex-export --export_type UPDATE --date 20210804` on stage and check the dip bucket for success. Can also update the time of the daily update cron job to a few minutes from now to see it run via cron. Will need to make sure there are correctly-named update files with today's date in the staging alma bucket for that to work.
NO
> Llama refactor

- Pipfile
- Pipfile.lock
- config/credit_card_slip_template.xml
- cron.d/credit-card-slips
- llama/alma.py
- llama/cli.py
- llama/credit_card_slips.py
- llama/s3.py
- llama/ses.py
- llama/ssm.py
- scripts/Credit-Card-Slips.sh
- tests/conftest.py
- tests/test_alma.py
- tests/test_cli.py
- tests/test_credit_card_slips.py
- tests/test_ses.py
- tests/test_ssm.py
* Add CLI command to send credit card slips email
* Add Alma module containing class with methods to request PO line records via the API
* Add module with functions to create credit card slips
* Add SES module containing class with methods to create and send an email with attachment
* Add SSM module containing class with method to get value from Parameter Store
* Add corresponding tests for CLI command, functions, and class methods
* Switch to defusedxml to fix potential security issues
* Add XML template for credit card slips
* Add bash script to run CLI command
* Add cron file for running bash script daily
Run tests with `pipenv run pytest`. With the proper SSM Parameter Store permissions, you can send the credit slips email to yourself with `pipenv run llama cc-slips --source_email …
> Create automated daily email of credit card slips to Tech Services staff

- cron.d/timdex-exports
Move the FULL export job to the 4th of the month rather than the 2nd, as the export may not be completed on the 2nd.
Following the merge of this PR, i will update the alma-sftp-ec2-prod instance to make sure the cron job change gets in place.
> Move the FULL export job to the 4th of the month

- cron.d/timdex-exports
We need to push the full update job back even farther because the job may not be completed until mid day on the 4th.  
This update pushes it to the 5th.
> Update to 5th because jobs can take this long

- config/credit_card_slip_template.xml
- llama/credit_card_slips.py
- tests/conftest.py
- tests/test_credit_card_slips.py
* Add function for getting total price
* Add unit tests for new functions
* Update XML template
* Update fixtures to accommodate new unit tests
Stakeholders requested a change in how the total price is obtained for the credit card slips. This was based on an item in the 09-07-2021 report where the total price was incorrect because 2 copies were purchased.
Run tests with `pipenv run pytest`. The format of the report is unaffected, this is just a backend change.
- https://mitlibraries.atlassian.net/jira/servicedesk/projects/INFRA/queues/custom/12/INFRA-177
NO
NO
> Add total price function based on updated info from stakeholder

- llama/credit_card_slips.py
- tests/conftest.py
- tests/test_credit_card_slips.py
* Ignore title spaces for when grabbing the first 3 characters for the invoice number
* Add corresponding unit test and fixture
This was requested by the stakeholders after discovering a title that began with "A star..." 
Run tests with `pipenv run pytest`. The format of the report is unaffected, this is just a backend change.
* https://mitlibraries.atlassian.net/browse/INFRA-184
NO
NO
> Ignore spaces in titles when creating invoice number

- README.md
- cron.d/timdex-exports
This PR updates the readme with some ssm information, and updates the cron job to completely disable the full update cron.
Information about this update is primarily recorded in the ticket linked below.  The short version is that the full update needs to be run only when the export has been completed, so its easier to run by hand when we see that happen for now.  
https://mitlibraries.atlassian.net/browse/IMP-2321
NO
NO
> Update readme and cron job

- llama/alma.py
- llama/sap.py
- tests/conftest.py
- tests/test_alma.py
extracts into a separate method of the Alma_API_Client the functionality to retrieve paged results from Alma API response. 
Adds this paging functionality to get_invoices_by_status and get_brief_po_lines methods
the Alma API returns paginated results with a maximum of 100 records per page. Some of our calls to the API may return more than 100 records total.
https://mitlibraries.atlassian.net/browse/IMP-2338
> extracts get_paged function

- patronload/scripts/pack_all_records.pl
- patronload/scripts/pack_sample_records.pl
- patronload/scripts/pick_random_files.pl
To help with future migration to Python, we need to thoroughly understand what the remaining Perl scripts do in the patron load process. This PR adds inline comments to the remaining Perl scripts in `patronload/scripts` documenting the code in detail
- https://mitlibraries.atlassian.net/browse/IMP-2318
NO
> Document patron load Perl scripts

- llama/alma.py
- process-invoices/print_reports_by_status.py
- tests/conftest.py
- tests/fixtures/invoices.json
- tests/test_alma.py
makes it possible to process more than 100+ invoices at a time for submission to SAP
- with more than 100 invoices ready to process, run print_reports_by_status following the instructions in invoice_steps.md 
- see that that correct number of invoices were processed
https://mitlibraries.atlassian.net/browse/DIP-](https://mitlibraries.atlassian.net/browse/ASI-29
> Get paged invoices

- llama/sap.py
- tests/conftest.py
- tests/test_sap.py
Why these changes are being introduced:
* This commit completes the refactor of make_summary.py by adding functionality to
generate summary reports from the Alma invoice data that can be sent to
Acquisitions Staff
How this addresses that need:
*  Adds a function in sap.py, generate_summary(), that generates a human-
readable report of data from an invoice data dict, structured
according to requirements provided by stakeholders.
*  information about invoices not being sent to SAP is included at the end of the reports
This was requested functionality that wasn't in make_summary.py and had previously
been done manually
*  Adds unit tests for new functionality.
Side effects of this change:
* The reports generated by this process are no longer printed to stdout.
Relevant ticket(s):
* …
> ASI-14 generate summary

- llama/__init__.py
- llama/alma.py
- llama/cli.py
- llama/config.py
- pytest.ini
- tests/conftest.py
- tests/test_alma.py
- tests/test_config.py
* Refactors `config.py` module to use class-based config with implementation based on env
* Adds checks for missing config values and production ssm path during config loading
* Moves config instantiation, along with logging and sentry configuration, to `__init__.py`
* Adds/updates tests for all changes
There is now a single location in the code, the `EXPECTED_CONFIG_VALUES` dict in `config.py`, where all expected config settings are tracked. This is useful as both in-code documentation and to enable configuration checks for staging and production deployment.
Try running `pipenv run llama` locally with various config settings set or unset in your .env to see the output. The application will not run without a `WORKSPACE` env variable, and if the `WORKSPACE` is stage or prod it also …
> Refactor to class-based config

- Pipfile.lock
- llama/sap.py
- tests/conftest.py
- tests/test_sap.py
Why these changes are being introduced:
Invoice data files sent to SAP must be accompanied by corresponding control files in a
particular format. See https://wikis.mit.edu/confluence/display/SAPdev/MIT+SAP+Dropbox
How this addresses that need:
* creates a function which takes an SAP data file (a string) and an invoice total for that data file
and returns a correctly formated control file (a string)
Relevant ticket(s):
* https://mitlibraries.atlassian.net/browse/ASI-13
> Generate sap control files

- cron.d/credit-card-slips
- cron.d/patron-load
- cron.d/timdex-exports
- process-invoices/invoice_steps.md
- scripts/Credit-Card-Slips.sh
- scripts/Full-Export.sh
- scripts/Patron-load.sh
- scripts/Update-Export.sh
This PR updates the cron jobs, and scripts used to run our jobs on the alma-sftp-ec2 instance to be simplified, and run in a new path.  
This PR is part of a larger change of how our ec2 instance runs,  we're switching to ubuntu 20, and simplifying the deployment as a part of the refactor of some of the code here.  
I remove the call to python 3.8 specifically here, as the system package is 3.8, and i think our intention is to manage versions in the pipfile, rather than with hard calls to system versions.  I dont know if this is for sure the best call to make here, but i'm hoping that this will be short lived enough not to matter.  
The vast majority of these changes are simple find/replaces.  
These changes correspond to changes in how we run code on the stage and prod instances.  They …
> Scripts update

- .github/pull-request-template.md
- llama/cli.py
- llama/config.py
- llama/sap.py
- tests/test_config.py
- tests/test_sap.py
Adds logic to generate and email summary files during a sap-invoices final run, or generate and log them in a dry final run.
Also updates the PR template and adds some extra error messages and checking during configuration loading.
Make sure that the following config values are set locally in your .env:
```
ALMA_API_URL: <Alma API URL>
SAP_REPLY_TO_EMAIL: <any email address>
SAP_REPORT_RECIPIENT_EMAILS: <your email address>
SAP_SUMMARY_RECIPIENT_EMAILS: <your email address>
SES_SEND_FROM_EMAIL: noreply@libraries.mit.edu
```
Then run the llama sap-invoice command. `pipenv run llama sap-invoices --final-run --dry-run` will now show summaries in the log output. The same command without the `--dry-run` flag will send you four emails: the two report (cover sheet) emails and the two summary …
> Email summary files, update config messages and PR template

- README.md
- llama/alma.py
- llama/cli.py
- llama/sample_data.py
- pytest.ini
- sample-data/sample-sap-invoice-data.json
- tests/conftest.py
- tests/fixtures/invoice_line.json
- tests/test_alma.py
- tests/test_cli.py
- tests/test_sample_data.py
* Adds a CLI command to create sandbox sap data
* Adds a sample_data module with the functionality needed to get or create vendors, create invoices, and create invoice lines
* Adds methods to the Alma_API_Client class for new API calls used by this feature
* Adds tests for all new functions, updates conftest and pytest.ini
* Update README to include instructions for creating sample data and then manually approving it in the Alma sandbox UI.
Running the sap-invoices command during development or staging runs requires there to be sample invoices in the sandbox that are ready to be paid. Rather than asking stakeholders to create sample invoices every time we need them or doing the entire creation manually ourselves, this automates at least the initial steps of creation, using consistent and …
> Add command to create sandbox sample data for SAP

- llama/sap.py
- tests/conftest.py
- tests/test_sap.py
Why these changes are being introduced:
The cost object and G/L account were incorrectly mapped from the API data.
Because of this these fields were in the wrong order in the SAP data file, leading
to that file being rejected when it was submitted.
How this addresses that need:
* corrects mapping from alma data
* updates tests and fixture data with the correct names
* updates reports so these fields remain in the
expected positions
Relevant ticket(s):
* https://mitlibraries.atlassian.net/browse/ASI-44
> Correct mapping to cost object and G/L account

- llama/sap.py
- tests/test_sap.py
* the way we were calculating the total amount for the control file
led to rounding errors in some cases
* uses fsum() to return an accurate sum of total amounts for the control file
* https://mitlibraries.atlassian.net/browse/ES-705
This fixes an issue where the calculation of the sum of the total amounts of invoices
could result in a rounding error.
NO, unless importing fsum() from the math module counts as a dependency.
NO
(not just this pull request message)
> fix rounding errors in total amount calculation

- llama/sap.py
- tests/conftest.py
- tests/test_sap.py
An incorrectly formatted PO Box address in Alma resulted in an error in SAP
After consultation with Accounts Payable it was determined that we could treat all
addresses as street address, which should prevent this error from happening in the future
and will simplify the code that formats address information for data files
* removes code which set the PO address indicator in the datafile
* updates code to consistently map address lines to datafile fields
* updates tests
* https://mitlibraries.atlassian.net/browse/ES-722
> treat all addresses as street addresses

- Pipfile
- Pipfile.lock
- llama/sap.py
- tests/conftest.py
- tests/test_sap.py
adds a check for multibyte-encoded characters in the invoice data
- paramiko has a bug which returns an error when we try to upload data files 
with multibyte characters
- SAP does not support multibyte-encoded characters
Delete this section if it isn't applicable to the PR.
- add a multibyte character to a vendor for a 'ready to be paid' invoice in alma staging
- do a dry-run using staging parameters
Delete this section if it isn't applicable to the PR.
https://mitlibraries.atlassian.net/browse/ES-742
YES
flatdict library - https://flatdict.readthedocs.io/en/stable/
NO
(not just this pull request message)
> Contains multibyte

- llama/sap.py
- tests/test_sap.py
when an invoice total was a decimal ending in 0, the 0 wasn't
being included in the string to which we converted the float
this specifies that the float should be formatted as a
string with two decimal places
Updates the test for this function to have an invoice total with
a decimal ending in a 0
https://mitlibraries.atlassian.net/browse/ES-763
YES | NO
YES | NO
(not just this pull request message)
> fixes bug in control file generation function

- llama/cli.py
- llama/sap.py
- tests/conftest.py
- tests/fixtures/invoice_with_over_encumbrance.json
- tests/fixtures/invoices.json
- tests/fixtures/vendor_multibyte-address.json
- tests/test_alma.py
- tests/test_sap.py
In certain situations the Alma API may return no fund data as the result of a fund query.
This causes an error where the code was expecting to have fund data.
* adds error handling to functions that retrieve funds and parse invoices
* invoices with fund errors or multibyte characters are moved into a separate
object to handle them more easily
* adds warnings to summary about funds for which data was not retrieved
* updates tests
* https://mitlibraries.atlassian.net/browse/ASI-46
Handles situations where the alma api returns zero funds in response to a fund query, 
specifically in cases where the fund has exceeded its overencumbrance limit.
create sample invoice data in the sandbox. edit one of the funds such that the over-encumbrance
limit is below the encumbered amount for the fund. …
> Handles fund errors and multibyte character errors

- config/credit_card_slip_template.xml
- llama/credit_card_slips.py
- tests/conftest.py
- tests/test_alma.py
- tests/test_credit_card_slips.py
There was an issue with the credit card slips automation not capturing the appropriate PO Lines at the beginning of the FY which was included in the [aggregator ticket](https://mitlibraries.atlassian.net/browse/ENSY-98). That issue seems to have resolved itself (without any clear reason) so nothing is included to address that.
There is a difference in the API behavior on our sandbox instance vs. our prod instance that neither Tania or I have been able to find an explanation for. On prod, PO Lines are retrieved by looking for a `status` of `ACTIVE`, despite the returned record having a status of `SENT`. This is how the integration was initially set up and we've not had any issues except for the brief interruption at the start of this FY. On the sandbox however, searching for `ACTIVE` …
> ENSY-98-acq-method-quantity

- patronload/student.py
patron year = 'U' is a possible value in records coming from datawarehouse, but is not covered by current code. According to the registrar’s office Patron year 'U' indicates “special student undergraduate i.e. non-degree students who are enrolled for the purpose of taking one or two courses."
According to IDLA, these students should be treated as normal undergraduates for the purpose of borrowing and should be assigned to the alma Undergraduate student user group '31'
* https://mitlibraries.atlassian.net/browse/ENSY-114
* adds U to mapping for “Student - Undergraduate” ( patron group code = 31)
- temporarily edit student.py such that it prints the MIT_ID for patrons with student_year == 'U' or 'u'
- run student.py
- find xml files in STUDENT folder for corresponding 'u' patrons
- for …
> map student_year value U to status 31
